version: "3.9"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: ./mysite
        target: /code
    ports:
      - "8000:5000"
  # redis:
  #   image: "redis:alpine"